#!/bin/bash
#SBATCH --partition=parallel
##SBATCH -A avankan
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --job-name=dedalus
#SBATCH --output=dedalus_output_%j
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp
module load anaconda

conda activate dedalus3

SUBMITDIR=$SLURM_SUBMIT_DIR
WORKDIR=/home/avankan/scr4_avankan/avankan/dedalus_codes/2D_Turbulence_Rotating_Sphere/dedalus_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cp -r 2D_Turbulence_Rotating_Sphere_sf.py "$WORKDIR" && cp -r plot_sphere_Mollweide.py "$WORKDIR" && cp -r plot_timeseries.py "$WORKDIR"  && cp -r plot_sphere.py "$WORKDIR"  && cp -r plot_spectrum.py "$WORKDIR" &&  cd "$WORKDIR" || exit -1 #cp -r X*_checkpoint_s1.h5 "$WORKDIR" && cd "$WORKDIR" || exit -1

mpiexec -n $SLURM_NTASKS python3 2D_Turbulence_Rotating_Sphere_sf.py
mpiexec -n $SLURM_NTASKS python3 plot_sphere_Mollweide.py snapshots/*.h5

cd "$SUBMITDIR" && cp dedalus_output_$SLURM_JOB_ID "$WORKDIR"
